
name: Create release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  make_release:
    runs-on: ubuntu-latest

    container:
      image: openapx/baseline-os:latest-ubuntu
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        ACTION_TOKEN: ${{ github.token }}
        VARS_COMPONENT: ${{ vars.COMPONENT }}

    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          apt-get install jq -y
          chmod u+rx-w .scripts/sas-createrelease.sh
      - name: Run create release script
        run: |
          .scripts/sas-createrelease.sh
          

